### ISSUE TITLE
OAuthPlayGround Login Issue

### ISSUE THREAD

**Issue by balaji-rajan** [pingidentity/pingidentity-devops-getting-started#73] opened 2019-08-26 15:43 UTC
**Describe the bug**
I'm not able to login and test OAuthPlayGround

**To Reproduce**
1. Go to https://localhost:9031/OAuthPlayground/welcome
2. Click on **Implict**
3. Provide User Credentials

**Logs**

> ERROR [SystemErr] Aug 26, 2019 2:21:05 PM com.unboundid.util.Debug debugLDAPResult
> [32mpingfederate_1     |[0m INFO: level="INFO" threadID=148 threadName="Connection reader for connection 34 in pool 'pingdirectory' to pingdirectory:389" ldapSDKVersion="4.0.11" revision="3
> 4e39aab27ea4fb92659a6888933db08099c7e41" connectionID=34 connectionPoolName="pingdirectory" connectedTo="pingdirectory:389" readLDAPResult="SearchResult(resultCode=50 (insufficient access rig
> hts), messageID=6, diagnosticMessage='The requested operation requires the config-read privilege')"

**Screenshots**
![image](https://user-images.githubusercontent.com/11008306/63702803-5839ea80-c845-11e9-96e9-d82fc6f78b3a.png)

**Environment:**
 - Github Repo: pingidentity-devops
 - Docker Container: Docker-Compose/ 01-SimpleStack (EDGE)
 - Local Environment : Windows 10

**Additional Info**
I was successfully able test all flow until last week, not sure if its related to new updates

**Comment by samir-gandhi** [comment] 2020-02-20 23:24
Hi, sorry for a late response. I've just tested and was unable to reproduce the error. 

note. for login information I used user.0/2FederateM0re

I assume if this was an error, it was fixed over time. I'm going to close this issue on the assumption it's fixed.

**Closed** 2020-02-20 23:25 UTC
Labels: bug
