### ISSUE TITLE
Bulk export utility Expose-parameters: duplicate substitution variable names (json path the same for multiple items)

### ISSUE THREAD

**Issue by shermanj38** [pingidentity/pingidentity-devops-getting-started#165] opened 2020-12-30 15:24 UTC
**Describe the bug**
While running the export utility with the default PF IN config, passwords for the listed native users in the Password credential Validators resource type are being substituted out with a duplicate variable name.  This is due to the users/passwords having the same json path, we need some method create unique variable names when the json path is the same for items in an array.

**To Reproduce**
1. in pf, have a simpleUsernamePasswordCredentialValidator with multiple users/passwords setup
2. Run the export utility using the default provided PF config file
3. in the rsulting subst export file, Go to the  "resourceType": "/passwordCredentialValidators" section, find your simpleUsernamePasswordCredentialValidator , and see that the substitution variable names for all of the users passwords have the same variable name.

**Expected behavior**
A unique variable name should be generated for all unique password fields.

**Screenshots**
This is a screenshot of the resulting "resourceType": "/passwordCredentialValidators" after an export, showing the duplicate password substitution variable name for different users, because the json path is the same
![image](https://user-images.githubusercontent.com/76571629/103363408-05032800-4a89-11eb-8628-008af49364d0.png)

**Environment:**
 - Github Repo: pingidentity/pingidentity-devops-getting-started
- Product: ping federate

**Additional Info**

**Comment by samir-gandhi** [comment] 2020-12-30 20:18
@ttranatping I've confirmed this behavior. 
this seems to be due to the simple PCV fields being formatted as an array in data.json vs a single object. I'd assume this makes it hard to use the name attribute from a different array item as the unique-identifier. 

this isn't an issue for the administrator users. 

here's the pf-config.json:
```
{
  "expose-parameters":[
    {
      "parameter-name": "encryptedValue",
      "replace-name": "value",
      "unique-identifiers": [
          "name"
      ]
    }
  ]
}
```

**Comment by ttranatping** [comment] 2021-01-13 11:57
Ok I've resolved it. Committed into master.

It now generates a config string such as: passwordCredentialValidators_items_simplePCV_configuration_tables_rows_fields_Username_jane_value
(where Username = jane)

Example config, where the "~" indicates that we want to resolve a UID from a peer where the current JSON object is an Array member:

{
      "parameter-name": "encryptedValue",
      "replace-name": "value",
      "unique-identifiers": [
          "name",
          "name~Username/value"
      ]
 }

**Closed by ttranatping** 2021-01-13 11:57 UTC
Labels: bug
